// <auto-generated />
using System;
using FairwayManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FairwayManager.Migrations
{
    [DbContext(typeof(FairwayManagerDBContext))]
    [Migration("20240402055533_AddBookingModel")]
    partial class AddBookingModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("FairwayManager.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerFourMembershipID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerOneMembershipID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerThreeMembershipID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerTwoMembershipID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TeeTime")
                        .HasColumnType("TEXT");

                    b.HasKey("BookingID");

                    b.HasIndex("PlayerFourMembershipID");

                    b.HasIndex("PlayerOneMembershipID");

                    b.HasIndex("PlayerThreeMembershipID");

                    b.HasIndex("PlayerTwoMembershipID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FairwayManager.Models.Member", b =>
                {
                    b.Property<int>("MembershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Handicap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.HasKey("MembershipID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("FairwayManager.Models.Booking", b =>
                {
                    b.HasOne("FairwayManager.Models.Member", "PlayerFour")
                        .WithMany()
                        .HasForeignKey("PlayerFourMembershipID");

                    b.HasOne("FairwayManager.Models.Member", "PlayerOne")
                        .WithMany()
                        .HasForeignKey("PlayerOneMembershipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FairwayManager.Models.Member", "PlayerThree")
                        .WithMany()
                        .HasForeignKey("PlayerThreeMembershipID");

                    b.HasOne("FairwayManager.Models.Member", "PlayerTwo")
                        .WithMany()
                        .HasForeignKey("PlayerTwoMembershipID");

                    b.Navigation("PlayerFour");

                    b.Navigation("PlayerOne");

                    b.Navigation("PlayerThree");

                    b.Navigation("PlayerTwo");
                });
#pragma warning restore 612, 618
        }
    }
}
